### PR TITLE
Fix compatibility issue and allow custom binary path

### PR DESCRIPTION
**Pull request by Khaleelhabeeb**
This pull request addresses the following:

1) compatibility issues: Ensures the code works with a Windows-compatible energibridge.exe binary placed in the bin/energibridge folder.

2) Custom binary path: Allows users to specify a custom path to the energibridge binary if needed.

Changes:
-Removed the mocking logic for the energibridge process.
-Implemented a _find_binary_path method to search for the binary in the expected location (bin/energibridge). It raises an error if the binary is not found.
-Modified the start method to use subprocess.Popen with platform-independent termination (terminate).
-Added error handling for potential issues like the binary not being found or failing to start/stop.
fixes issue #1

### CODE REVIEW

**Comment by luiscruz** [comment]
Hi @Khaleelhabeeb thanks for this pull request.
I've skimmed through the code and it seems to get the job done!!
I will test it later today and then I'll accept the PR.
One thing I'll have to check is whether EnergiBridge is properly handling the SIGTERM signal called by `terminate()`. Anyway, I like the solution of using terminate because it's cross platform.
I'll keep you posted!

**Comment by luiscruz** [comment]
Thanks for this pull request @Khaleelhabeeb 
To completely fix #1 it would be nice to allow users to set their own path to EnergiBridge, for example using a config file.
Such a config file could be present in the user directory or in the directory of a project that uses this library.

**Comment by Khaleelhabeeb** [comment]
yeah allowing users to set thier own path will solve the issue and will be the best approach

**Comment by luiscruz** [comment]
I'm working on it. It's on #5

**Pull request merged**
